---
title: "Day 4 Exploring Data"
author: "Carlo Broderick"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

# Exploratory Data Visualization

Check out your data a bit

```{r}
#| include: false

# Tell me the column names

names(penguins)

# Dimensions
dim(penguins)

# Fist Six Lines
head(penguins)

# Last six lines
tail(penguins)
```

```{r}

#|warning: false
#overview of data
skim(penguins)

#even more exploration of data
GGally::ggpairs(penguins)



```

## Jitterplot

Flipper length by species

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(width = 0.2,
              alpha = 0.5,
              aes(color = species)) +
  geom_boxplot(fill = NA) +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) +
  labs(x = "Pengine Species",
       y = "Flipper Length",
       title = "Palmer Archipelago Penguin Flippers")
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) + 
  geom_histogram(aes(fill = species),color = "magenta") +
  facet_wrap(~species, ncol = 1)
```
